### ISSUE TITLE
Does not appear to call end() when an error was encountered

### ISSUE THREAD

**Issue by JeffML** [safonovpro/node-html-crawler#1]
I think the most common use case would be to crawl a site and note the number of broken links.  However, it looks like if a broken link is encountered, an 'error' event is thrown, the crawler crawls on, but 'end' is not called.  If no broken links are encountered, then the 'end' event IS emitted.

**Comment by JeffML** [comment]
If I override _generateEvents, moving a couple of lines:

```
Crawler.prototype._generateEvents =  function (eventsType, data) {
  this.countOfProcessedUrls++;   // this line moved
  if(eventsType === 'data') {
      this.emit('data', {url: data.currentUrl, result: data.result});
  } else if(eventsType === 'error') {
      this.emit('error', new Error(`Error in ${data.currentUrl}: ${data.error}`));
  }
  if(this.waitingOfConnection === 0 && this.countOfProcessedUrls === this.foundLinks.size) this.emit('end');  // this line moved
}
```

Then the 'end' event is emitted, regardless of errors.

**Comment by safonovpro** [comment]
All broken links are marked with the corresponding HTTP status (4xx, 5xx, etc.). The "end" event fires only after traversing all found links. See the results of [examples/check-ex-links-on-domain.js](https://github.com/safonovpro/node-html-crawler/blob/master/examples/check-ex-links-on-domain.js).

**Comment by JeffML** [comment]
The end event doesn't fire if any 'error' event is emitted. I can send you
test code to try if you want.

**Comment by safonovpro** [comment]
Yes, this is possible... It is planned to release version 2.0, where including this will be fixed.

**Comment by safonovpro** [comment]
Thanks! Fixed in branch v2: https://github.com/safonovpro/node-html-crawler/commit/4a61bbb0eff3db43875b137566ffbd0eb28f73eb

**Comment by safonovpro** [comment]
> If I override _generateEvents, moving a couple of lines:
> 
> ```
> Crawler.prototype._generateEvents =  function (eventsType, data) {
>   this.countOfProcessedUrls++;   // this line moved
>   if(eventsType === 'data') {
>       this.emit('data', {url: data.currentUrl, result: data.result});
>   } else if(eventsType === 'error') {
>       this.emit('error', new Error(`Error in ${data.currentUrl}: ${data.error}`));
>   }
>   if(this.waitingOfConnection === 0 && this.countOfProcessedUrls === this.foundLinks.size) this.emit('end');  // this line moved
> }
> ```
> 
> Then the 'end' event is emitted, regardless of errors.

Thanks! Fixed in branch v2: https://github.com/safonovpro/node-html-crawler/commit/4a61bbb0eff3db43875b137566ffbd0eb28f73eb
