### ISSUE TITLE
Sending many requests error

### ISSUE THREAD

**Issue by zxcvpn** [safonovpro/node-html-crawler#8]
- When I'm trying to scrap site like www.facebook.com - the module automatically sending many requests i don't know where's the wrong
> Here's my code
````
const http = require("http");
const Crawler = require('node-html-crawler');

http.createServer((req,res) => { 
    const crawler = new Crawler({
        protocol: 'https:',
        domain: 'www.facebook.com/'
    });
   crawler.crawl();
   crawler.on("data", function (data) { 
        console.log(data);
    })
}).listen(3000);
````
> Here's The Image
![Screenshot_20210318-105548](https://user-images.githubusercontent.com/75979092/111599223-bab45c00-87d8-11eb-88af-d8cd3bccfe53.png)

- I set the result to undefined property to show you the error

**Comment by safonovpro** [comment]
Hi @zxcvpn, here is an example of working code:

```js
const Crawler = require('node-html-crawler');

const crawler = new Crawler({
    protocol: 'https:',
    domain: 'www.facebook.com', // you have a slash at the end - this is an error
    // this will slow down the process
    limitForConnections: 1,
    timeout: 3000,
});

crawler.crawl();
crawler.on('data', (data) => console.log(data.result.statusCode, data.url));
crawler.on('error', (error) => console.error(error));
crawler.on('end', () => console.log(`Finish! All urls on domain ${domain} a crawled!`));
```

**Comment by zxcvpn** [comment]
- It's going every where in Facebook not just to the required page and it's cannot stop by him self when it's finished needed page it's continue loading pages from every where 

![Screenshot_20210321-113257](https://user-images.githubusercontent.com/75979092/111900291-58f32c80-8a3a-11eb-947b-54d25bf35213.png)
